package com.manuhd.app.tarjetas.model;

public enum TipoPlantilla {
    LLEGADA_MADRID,
    LLEGADA_FUERA,
    ALTA_SOCIO,
    ALTA_PETROLERA,
    ALTA_APROBADA,
    ALTA_RECHAZADA,
    BAJA_SOCIO,
    BAJA_CONFIRMADA,
    DUPLICADO_SOCIO,
    DUPLICADO_CONFIRMADA,
    DUPLICADO_PETROLERA
}
